//to use desired version
terraform {
  required_providers {
    local = {
      source = "hashicorp/local"
      version = "2.2.2"
      //version = "!2.0.0" dont use this version
      //version = " > 1.1.0" greater than
      //version = "> 1.2.0, < 2.0.0, !=1.4.0" in range
    }
  }
}

resource "local_file" "pet" {
    //filename = var.filename[count.index]
    filename = each.value
    content = "My favorite pet is ${random_pet.my-pet.id}"
    file_permission = "0700"
    //content2 = data.local_file.dog.content
    //count = length(var.filename)
    for_each = toset(var.filename)
    // if there is some changes, first create then destroy old one
    lifecycle {
      create_before_destroy = true
    }

    // if there is some changes, protect the old one
    # lifecycle {
    #   prevent_destroy = true
    # }

    // ignore the changes on this attribute
    # lifecycle {
    #   ignore_changes = [
    #     content 
    #   ]
    # }
}

resource "random_pet" "my-pet" {
    prefix = var.prefix
    separator = var.separator
    length = var.length
}

output "pet-name" {
  value = random_pet.my-pet.id
  description = "Record the value of pet Id generated by the random_pet resource"
}

output "pets" {
  value = local_file.pet
  sensitive = true
}

# data "local-file" "dog" {
#   filename = "/root/dog.txt"
# }